/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Home */
        get: operations["home__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/analyze-recording": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analyze Recording */
        post: operations["analyze_recording_api_analyze_recording_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Config */
        get: operations["get_config_api_config_get"];
        put?: never;
        /** Update Config */
        post: operations["update_config_api_config_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/config/api-key": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Clear Api Key */
        delete: operations["clear_api_key_api_config_api_key_delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/generate-text": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Text */
        post: operations["generate_text_api_generate_text_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get History */
        get: operations["get_history_api_history_get"];
        put?: never;
        /** Save History Session */
        post: operations["save_history_session_api_history_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/history/{session_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get History Session */
        get: operations["get_history_session_api_history__session_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Body_analyze_recording_api_analyze_recording_post */
        Body_analyze_recording_api_analyze_recording_post: {
            /** Audio */
            audio: string;
            /**
             * Metadata
             * @default {}
             */
            metadata: string;
        };
        /** ConfigUpdatePayload */
        ConfigUpdatePayload: {
            /** Analysis Language */
            analysis_language: string;
            gemini: components["schemas"]["GeminiConfigUpdate"];
            /** Keep Last Audio */
            keep_last_audio: boolean;
            langfuse: components["schemas"]["LangfuseConfigUpdate"];
            /** Same Language For Analysis */
            same_language_for_analysis: boolean;
            /** Session Limit */
            session_limit: number;
            /** Text Language */
            text_language: string;
            /** Ui Language */
            ui_language: string;
        };
        /** ExerciseGenerationRequest */
        ExerciseGenerationRequest: {
            /** Analysis Language */
            analysis_language: string;
            /** Language */
            language: string;
            /** Topic Prompt */
            topic_prompt: string;
        };
        /** ExerciseGenerationResponse */
        ExerciseGenerationResponse: {
            /** Analysis Language */
            analysis_language: string;
            /** Language */
            language: string;
            /** Text */
            text: string;
            /** Topic Prompt */
            topic_prompt: string;
        };
        /** GeminiConfigUpdate */
        GeminiConfigUpdate: {
            /** Analysis Model */
            analysis_model: string;
            /** Api Key */
            api_key?: string | null;
            /** Same Model For Analysis */
            same_model_for_analysis: boolean;
            /** Text Model */
            text_model: string;
            /**
             * Text Thinking Level
             * @enum {string}
             */
            text_thinking_level: "low" | "medium" | "high";
        };
        /** GeminiModelCatalogEntry */
        GeminiModelCatalogEntry: {
            /** Free Tier Requests Per Day Hint */
            free_tier_requests_per_day_hint: number | null;
            /** Id */
            id: string;
            /** Label */
            label: string;
        };
        /** GeminiPublicConfig */
        GeminiPublicConfig: {
            /** Analysis Model */
            analysis_model: string;
            /**
             * Api Key Source
             * @enum {string}
             */
            api_key_source: "env" | "stored" | "none";
            /** Available Models */
            available_models: components["schemas"]["GeminiModelCatalogEntry"][];
            /** Has Api Key */
            has_api_key: boolean;
            /** Model */
            readonly model: string;
            /** Same Model For Analysis */
            same_model_for_analysis: boolean;
            /** Text Model */
            text_model: string;
            /**
             * Text Thinking Level
             * @enum {string}
             */
            text_thinking_level: "low" | "medium" | "high";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Hesitation */
        Hesitation: {
            /** End */
            end: number;
            /** Note */
            note: string;
            /** Start */
            start: number;
        };
        /** HistorySession */
        HistorySession: {
            analysis: components["schemas"]["SessionAnalysis"];
            /** Analysis Language */
            analysis_language?: string | null;
            /** Created At */
            created_at: string;
            /** Id */
            id: string;
            /** Language */
            language: string;
            /** Text */
            text: string;
            /** Topic Prompt */
            topic_prompt?: string | null;
        };
        /** HistoryStore */
        HistoryStore: {
            /** Sessions */
            sessions?: components["schemas"]["HistorySession"][];
            /**
             * Version
             * @default 1
             * @constant
             */
            version: 1;
        };
        /** LangfuseConfigUpdate */
        LangfuseConfigUpdate: {
            /** Host */
            host?: string | null;
            /** Public Key */
            public_key?: string | null;
            /** Secret Key */
            secret_key?: string | null;
        };
        /** LangfusePublicConfig */
        LangfusePublicConfig: {
            /** Enabled */
            enabled: boolean;
            /** Has Public Key */
            has_public_key: boolean;
            /** Has Secret Key */
            has_secret_key: boolean;
            /** Host */
            host: string | null;
            /**
             * Public Key Source
             * @enum {string}
             */
            public_key_source: "env" | "stored" | "none";
            /**
             * Secret Key Source
             * @enum {string}
             */
            secret_key_source: "env" | "stored" | "none";
        };
        /** PublicConfigView */
        PublicConfigView: {
            /** Analysis Language */
            analysis_language: string;
            gemini: components["schemas"]["GeminiPublicConfig"];
            /** Keep Last Audio */
            keep_last_audio: boolean;
            langfuse: components["schemas"]["LangfusePublicConfig"];
            /** Same Language For Analysis */
            same_language_for_analysis: boolean;
            /** Session Limit */
            session_limit: number;
            /** Text Language */
            text_language: string;
            /** Ui Language */
            ui_language: string;
            /** Version */
            version: number;
        };
        /** RecordingAnalysisResult */
        RecordingAnalysisResult: {
            analysis: components["schemas"]["SessionAnalysis"];
            review: components["schemas"]["RecordingReview"];
        };
        /** RecordingReview */
        RecordingReview: {
            /** Clarity */
            clarity: string;
            /** Hesitations */
            hesitations?: string[];
            /** Pace */
            pace: string;
            /** Recommendations */
            recommendations?: string[];
            /** Summary */
            summary: string;
        };
        /** SessionAnalysis */
        SessionAnalysis: {
            /** Clarity Score */
            clarity_score: number;
            /** Hesitations */
            hesitations?: components["schemas"]["Hesitation"][];
            /** Pace Score */
            pace_score: number;
            /** Summary */
            summary?: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    home__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    analyze_recording_api_analyze_recording_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_analyze_recording_api_analyze_recording_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecordingAnalysisResult"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_config_api_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicConfigView"];
                };
            };
        };
    };
    update_config_api_config_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConfigUpdatePayload"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicConfigView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    clear_api_key_api_config_api_key_delete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PublicConfigView"];
                };
            };
        };
    };
    generate_text_api_generate_text_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExerciseGenerationRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExerciseGenerationResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
    get_history_api_history_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryStore"];
                };
            };
        };
    };
    save_history_session_api_history_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["HistorySession"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryStore"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_history_session_api_history__session_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistorySession"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
